DROP TABLE EMS_BATCH_EXECUTION CASCADE CONSTRAINTS;
DROP TABLE EMS_MARKETSEGMENT CASCADE CONSTRAINTS;
DROP TABLE EMS_INSTRUMENT_SECTOR CASCADE CONSTRAINTS;
DROP TABLE EMS_UTIL_CURRENCY CASCADE CONSTRAINTS;
DROP TABLE EMS_INSTRUMENT CASCADE CONSTRAINTS;
DROP TABLE REVINFO CASCADE CONSTRAINTS;
DROP SEQUENCE HIBERNATE_SEQUENCE ;
DROP TABLE EMS_VENUE CASCADE CONSTRAINTS;
DROP TABLE EMS_INST_SEC_VENUE CASCADE CONSTRAINTS;
DROP TABLE EMS_UTIL_CALENDAR CASCADE CONSTRAINTS;
DROP TABLE EMS_PRODUCTINSTRUMENTS CASCADE CONSTRAINTS;
DROP TABLE EMS_INSTRUMENT_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE EMS_INQUIRY_TRADINGPROTOCOL CASCADE CONSTRAINTS;
DROP TABLE EMS_PRODUCTPROTOCOLS CASCADE CONSTRAINTS;


------AUDIT TABLES -------
DROP TABLE EMS_BATCH_EXECUTION_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_VENUE_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_INST_SEC_VENUE_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_UTIL_CURRENCY_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_INSTRUMENT_SECTOR_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_INSTRUMENT_AUD CASCADE CONSTRAINTS; 
DROP TABLE EMS_MARKETSEGMENT_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_PRODUCTINSTRUMENTS_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_INSTRUMENT_PRODUCT_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_UTIL_CALENDAR_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_INQUIRY_TRADPROTOCOL_AUD CASCADE CONSTRAINTS;
DROP TABLE EMS_PRODUCTPROTOCOLS_AUD CASCADE CONSTRAINTS;
------AUDIT TABLES -------

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;


  CREATE TABLE EMS_BATCH_EXECUTION (
    BATCH_NAME VARCHAR2(50 ), 
	EXECUTION_START_TIME TIMESTAMP (6), 
	EXECUTION_END_TIME TIMESTAMP (6), 
	ROWS_PROCESSED NUMBER
	) ;
ALTER TABLE EMS_BATCH_EXECUTION ADD CONSTRAINT BATCH_EXECUTION_PK PRIMARY KEY (BATCH_NAME);

CREATE TABLE EMS_MARKETSEGMENT (	
    ID NUMBER NOT NULL ENABLE, 
	MARKETSEGMENT VARCHAR2(4 ) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	POSTTRADEMARKETSEGMENT VARCHAR2(15 ) 
);
   
ALTER TABLE EMS_MARKETSEGMENT ADD CONSTRAINT EMS_MARKETSEGMENT_PK PRIMARY KEY (ID);
   
   
CREATE TABLE EMS_INSTRUMENT_SECTOR (
    ID            NUMBER        NOT NULL ENABLE,
    DESCRIPTION   VARCHAR2(50)        NOT NULL ENABLE,
    SEQUENCE      NUMBER        NOT NULL ENABLE,
    TYPE          VARCHAR2(10) DEFAULT 'BOND'        NOT NULL ENABLE,
    SHORTNAME     VARCHAR2(11)
);

ALTER TABLE EMS_INSTRUMENT_SECTOR ADD CONSTRAINT PK_EMS_INSTRUMENT_SECTOR PRIMARY KEY ( ID );


CREATE TABLE EMS_UTIL_CURRENCY (
    ISOCODE          CHAR(3)        NOT NULL ENABLE,
    LONGNAME         VARCHAR2(250)        NOT NULL ENABLE,
    SHORTNAME        CHAR(3)        NOT NULL ENABLE,
    PREPENDSYMBOL    CHAR(1)        NOT NULL ENABLE,
    APPENDSYMBOL     CHAR(1)        NOT NULL ENABLE,
    MINORUNIT        NUMBER        NOT NULL ENABLE,
    TEXTSYMBOL       VARCHAR2(4),
    UNICODESYMBOL    VARCHAR2(32),
    POSTFIXSYMBOL    VARCHAR2(32),
    MFD_FXRATE_EUR   NUMBER
);

ALTER TABLE EMS_UTIL_CURRENCY ADD CONSTRAINT PK_EMS_UTIL_CURRENCY PRIMARY KEY ( ISOCODE );

  CREATE TABLE EMS_INSTRUMENT 
   (	ID NUMBER NOT NULL ENABLE, 
	ISIN CHAR(12 ), 
	CUSIP CHAR(9 ), 
	CINS CHAR(9 ), 
	BONDTYPE CHAR(1 ), 
	TRACECODE CHAR(1 ), 
	SHORTNAME VARCHAR2(100 ), 
	TICKER VARCHAR2(15 ), 
	COUPON NUMBER, 
	COUPONFREQUENCY CHAR(1 ), 
	COUPONTYPE CHAR(1 ), 
	MATURITYDATE DATE, 
	ISSUEDATE DATE, 
	ACCRUALSTARTDATE DATE, 
	NEXTPAYMENTDATE DATE, 
	ISSUEAMOUNT NUMBER, 
	AMOUNTOUTSTANDING NUMBER, 
	ISOCURRENCYCODE CHAR(3 ), 
	COUNTRY CHAR(2 ), 
	ISSUER VARCHAR2(255 ), 
	SECTORID NUMBER, 
	DEBTCLASSIFICATION VARCHAR2(20 ), 
	MOODYRATING VARCHAR2(10 ), 
	SNPRATING VARCHAR2(10 ), 
	NEXTCALLDATE DATE, 
	NEXTCALLPRICE NUMBER, 
	NEXTPUTDATE DATE, 
	BENCHMARKID NUMBER, 
	CALCFLAG CHAR(1 ), 
	DV01WORST NUMBER, 
	MODIFIEDDURATIONWORST NUMBER, 
	MARKETSEGMENT NUMBER, 
	ISDELETED CHAR(1 ), 
	UPDATETS TIMESTAMP (6), 
	MINLOTSIZE NUMBER, 
	DENOMINCR NUMBER, 
	ON_MAEL CHAR(1 ), 
	ON_MTXX CHAR(1 ), 
	ON_MASG CHAR(1 ), 
	ON_MANL CHAR(1 )	 
   )  ;

ALTER TABLE EMS_INSTRUMENT ADD CONSTRAINT EMS_INSTRUMENT_PK PRIMARY KEY (ID);
ALTER TABLE EMS_INSTRUMENT ADD	(CONSTRAINT EMS_INSTRUMENT_FK FOREIGN KEY (MARKETSEGMENT)
	  REFERENCES EMS_MARKETSEGMENT (ID) ENABLE, 
	 CONSTRAINT EMS_INSTRUMENTSECTOR_FK FOREIGN KEY (SECTORID)
	  REFERENCES EMS_INSTRUMENT_SECTOR (ID) ENABLE, 
	 CONSTRAINT EMS_INSTRUMENTCURRENCY_FK FOREIGN KEY (ISOCURRENCYCODE)
	  REFERENCES EMS_UTIL_CURRENCY (ISOCODE) ENABLE);
   
CREATE INDEX EMS_INST_DATA_I1 ON EMS_INSTRUMENT (ISIN);

CREATE INDEX EMS_INST_DATA_I2 ON EMS_INSTRUMENT (CUSIP);

CREATE TABLE EMS_VENUE (
    ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(20 )
   );
ALTER TABLE EMS_VENUE ADD CONSTRAINT PK_EMS_VENUE PRIMARY KEY (ID);

CREATE TABLE EMS_INST_SEC_VENUE (
    INST_ID    NUMBER        NOT NULL ENABLE,
    VENUE_ID   NUMBER        NOT NULL ENABLE
);

ALTER TABLE EMS_INST_SEC_VENUE ADD (
    CONSTRAINT FK_INST_ID FOREIGN KEY ( INST_ID ) REFERENCES EMS_INSTRUMENT ( ID )    ENABLE,
    CONSTRAINT FK_INST_VENUE_ID FOREIGN KEY ( VENUE_ID ) REFERENCES EMS_VENUE ( ID ) ENABLE
);

CREATE TABLE EMS_UTIL_CALENDAR (
	CALENDARID NUMBER NOT NULL ENABLE, 
	CODE VARCHAR2(4 ), 
	DESCRIPTION VARCHAR2(50 ), 
	DISPLAYNAME VARCHAR2(50 )
   ) ;
ALTER TABLE EMS_UTIL_CALENDAR ADD CONSTRAINT PK_EMS_UTIL_CALENDARL PRIMARY KEY (CALENDARID);

CREATE TABLE EMS_INSTRUMENT_PRODUCT (
	ID NUMBER NOT NULL ENABLE, 
	MARKETSEGMENTID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	PRODUCT_CD CHAR(4 ), 
	CALENDARID NUMBER DEFAULT 0, 
	STLDAYS NUMBER DEFAULT 3 NOT NULL ENABLE, 
	FXSTLDAYS NUMBER DEFAULT 3 NOT NULL ENABLE, 
	ISDELETED CHAR(1 ) DEFAULT 'N' NOT NULL ENABLE
   );
   
ALTER TABLE EMS_INSTRUMENT_PRODUCT ADD CONSTRAINT PK_INSTRUMENT_PRODUCT PRIMARY KEY (ID);
ALTER TABLE EMS_INSTRUMENT_PRODUCT ADD (
	 CONSTRAINT FK_INSTRUMENT_PROD_MS FOREIGN KEY (MARKETSEGMENTID)
	  REFERENCES EMS_MARKETSEGMENT (ID) ENABLE, 
	 CONSTRAINT FK_INST_PROD_CAL_ID FOREIGN KEY (CALENDARID)
	  REFERENCES EMS_UTIL_CALENDAR (CALENDARID) ENABLE);

CREATE TABLE EMS_PRODUCTINSTRUMENTS 
   (	INSTRUMENTID NUMBER NOT NULL ENABLE, 
	PRODUCTID NUMBER NOT NULL ENABLE, 
	ISDEFAULT CHAR(1 ), 
	PRIORITY NUMBER(*,0)
   );

ALTER TABLE EMS_PRODUCTINSTRUMENTS ADD CONSTRAINT EMS_PRODUCTINSTRUMENTS_PK PRIMARY KEY (INSTRUMENTID, PRODUCTID);  
ALTER TABLE EMS_PRODUCTINSTRUMENTS ADD (
	CONSTRAINT EMS_PRODUCTINSTRUMENTS_FK FOREIGN KEY (INSTRUMENTID)
	  REFERENCES EMS_INSTRUMENT (ID) ENABLE,
      CONSTRAINT EMS_PROD_FK FOREIGN KEY (PRODUCTID)
      REFERENCES EMS_INSTRUMENT_PRODUCT(ID) ENABLE);
      
 
CREATE TABLE EMS_INQUIRY_TRADINGPROTOCOL 
   (	TRADINGPROTOCOLID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	SHORTNAME VARCHAR2(15 ), 
	APINAME VARCHAR2(10 )
	) ;

ALTER TABLE EMS_INQUIRY_TRADINGPROTOCOL ADD CONSTRAINT PK_INQUIRY_TRADINGPROTOCOL PRIMARY KEY (TRADINGPROTOCOLID);

  
CREATE TABLE EMS_PRODUCTPROTOCOLS(	
    ID NUMBER, 
	PRODUCTID NUMBER NOT NULL ENABLE, 
	INQUIRYTYPE CHAR(1 ), 
	PRICETYPE CHAR(1 ), 
	TRANSACTIONTYPE VARCHAR2(8 ), 
	PROTOCOLID NUMBER, 
	FORCERANK NUMBER NOT NULL ENABLE
 ) ;

ALTER TABLE EMS_PRODUCTPROTOCOLS ADD CONSTRAINT PK_EMS_PRODPROTOCOLS PRIMARY KEY (ID);
   
ALTER TABLE EMS_PRODUCTPROTOCOLS ADD (
   CONSTRAINT EMS_PROD_PROT_FK FOREIGN KEY(PRODUCTID)
   REFERENCES EMS_INSTRUMENT_PRODUCT(ID),
   CONSTRAINT EMS_INQ_PROTOCOL_FK FOREIGN KEY(PROTOCOLID)
   REFERENCES EMS_INQUIRY_TRADINGPROTOCOL(TRADINGPROTOCOLID)
   );

-----AUDIT TABLES -----

CREATE TABLE REVINFO
(
REV NUMBER NOT NULL,
REVTSTMP NUMBER,
CONSTRAINT REVINFO_PKEY PRIMARY KEY (REV)
);

 CREATE TABLE EMS_INSTRUMENT_AUD 
   (	ID NUMBER NOT NULL ENABLE, 
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	ISIN CHAR(12 ), 
	CUSIP CHAR(9 ), 
	CINS CHAR(9 ), 
	BONDTYPE CHAR(1 ), 
	TRACECODE CHAR(1 ), 
	SHORTNAME VARCHAR2(100 ), 
	TICKER VARCHAR2(15 ), 
	COUPON NUMBER, 
	COUPONFREQUENCY CHAR(1 ), 
	COUPONTYPE CHAR(1 ), 
	MATURITYDATE DATE, 
	ISSUEDATE DATE, 
	ACCRUALSTARTDATE DATE, 
	NEXTPAYMENTDATE DATE, 
	ISSUEAMOUNT NUMBER, 
	AMOUNTOUTSTANDING NUMBER, 
	ISOCURRENCYCODE CHAR(3 ), 
	COUNTRY CHAR(2 ), 
	ISSUER VARCHAR2(255 ), 
	SECTORID NUMBER, 
	DEBTCLASSIFICATION VARCHAR2(20 ), 
	MOODYRATING VARCHAR2(10 ), 
	SNPRATING VARCHAR2(10 ), 
	NEXTCALLDATE DATE, 
	NEXTCALLPRICE NUMBER, 
	NEXTPUTDATE DATE, 
	BENCHMARKID NUMBER, 
	CALCFLAG CHAR(1 ), 
	DV01WORST NUMBER, 
	MODIFIEDDURATIONWORST NUMBER, 
	MARKETSEGMENT NUMBER, 
	ISDELETED CHAR(1 ), 
	UPDATETS TIMESTAMP (6), 
	MINLOTSIZE NUMBER, 
	DENOMINCR NUMBER, 
	ON_MAEL CHAR(1 ), 
	ON_MTXX CHAR(1 ), 
	ON_MASG CHAR(1 ), 
	ON_MANL CHAR(1 )	 
   )  ;
   
ALTER TABLE EMS_INSTRUMENT_AUD ADD CONSTRAINT EMS_INSTRUMENT_AUD_rev FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_VENUE_AUD (
    ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(20 ),
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1)
   );
ALTER TABLE EMS_VENUE_AUD ADD CONSTRAINT EMS_VENUE_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_INST_SEC_VENUE_AUD (
    INST_ID    NUMBER        NOT NULL ENABLE,
    VENUE_ID   NUMBER        NOT NULL ENABLE,
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1)
);
ALTER TABLE EMS_INST_SEC_VENUE_AUD ADD CONSTRAINT EMS_INST_SEC_VENUE_AUD_R FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_INSTRUMENT_SECTOR_AUD (
    ID            NUMBER        NOT NULL ENABLE,
    DESCRIPTION   VARCHAR2(50)        NOT NULL ENABLE,
    SEQUENCE      NUMBER        NOT NULL ENABLE,
    TYPE          VARCHAR2(10) DEFAULT 'BOND'        NOT NULL ENABLE,
    SHORTNAME     VARCHAR2(11),
     REV NUMBER NOT NULL,
    REVTYPE NUMBER(1)
);

ALTER TABLE EMS_INSTRUMENT_SECTOR_AUD ADD CONSTRAINT EMS_INST_SECT_AUD_rEV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_UTIL_CURRENCY_AUD (
    ISOCODE          CHAR(3)        NOT NULL ENABLE,
    LONGNAME         VARCHAR2(250)        NOT NULL ENABLE,
    SHORTNAME        CHAR(3)        NOT NULL ENABLE,
    PREPENDSYMBOL    CHAR(1)        NOT NULL ENABLE,
    APPENDSYMBOL     CHAR(1)        NOT NULL ENABLE,
    MINORUNIT        NUMBER        NOT NULL ENABLE,
    TEXTSYMBOL       VARCHAR2(4),
    UNICODESYMBOL    VARCHAR2(32),
    POSTFIXSYMBOL    VARCHAR2(32),
    MFD_FXRATE_EUR   NUMBER,
     REV NUMBER NOT NULL,
    REVTYPE NUMBER(1)
);

ALTER TABLE EMS_UTIL_CURRENCY_AUD ADD CONSTRAINT EMS_UTIL_CURR_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_MARKETSEGMENT_AUD (	
    ID NUMBER NOT NULL ENABLE, 
       REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	MARKETSEGMENT VARCHAR2(4 ) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	POSTTRADEMARKETSEGMENT VARCHAR2(15 )
);

ALTER TABLE EMS_MARKETSEGMENT_AUD ADD CONSTRAINT EMS_MARKETSEGMENT_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_UTIL_CALENDAR_AUD (
	CALENDARID NUMBER NOT NULL ENABLE, 
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	CODE VARCHAR2(4 ), 
	DESCRIPTION VARCHAR2(50 ), 
	DISPLAYNAME VARCHAR2(50 )
   ) ;
ALTER TABLE EMS_UTIL_CALENDAR_AUD ADD CONSTRAINT EMS_UTIL_CALENDAR_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;   
  
CREATE TABLE EMS_INSTRUMENT_PRODUCT_AUD (
	ID NUMBER NOT NULL ENABLE,
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	MARKETSEGMENTID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	PRODUCT_CD CHAR(4 ), 
	CALENDARID NUMBER DEFAULT 0, 
	STLDAYS NUMBER DEFAULT 3 NOT NULL ENABLE, 
	FXSTLDAYS NUMBER DEFAULT 3 NOT NULL ENABLE, 
	ISDELETED CHAR(1 ) DEFAULT 'N' NOT NULL ENABLE
   );
ALTER TABLE EMS_INSTRUMENT_PRODUCT_AUD ADD CONSTRAINT EMS_INST_PROD_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;     

CREATE TABLE EMS_PRODUCTINSTRUMENTS_AUD 
   (	INSTRUMENTID NUMBER NOT NULL ENABLE,
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	PRODUCTID NUMBER NOT NULL ENABLE, 
	ISDEFAULT CHAR(1 ), 
	PRIORITY NUMBER(*,0)
   );

ALTER TABLE EMS_PRODUCTINSTRUMENTS_AUD ADD CONSTRAINT EMS_PRODINST_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

  
CREATE TABLE EMS_INQUIRY_TRADPROTOCOL_AUD 
   (	TRADINGPROTOCOLID NUMBER NOT NULL ENABLE, 
   REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	DESCRIPTION VARCHAR2(32 ), 
	SHORTNAME VARCHAR2(15 ), 
	APINAME VARCHAR2(10 )
	) ;
    
ALTER TABLE EMS_INQUIRY_TRADPROTOCOL_AUD ADD CONSTRAINT EMS_INQ_TRADPROT_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE EMS_PRODUCTPROTOCOLS_AUD(	
    ID NUMBER, 
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	PRODUCTID NUMBER NOT NULL ENABLE, 
	INQUIRYTYPE CHAR(1 ), 
	PRICETYPE CHAR(1 ), 
	TRANSACTIONTYPE VARCHAR2(8 ), 
	PROTOCOLID NUMBER, 
	FORCERANK NUMBER NOT NULL ENABLE
 ) ;
ALTER TABLE EMS_PRODUCTPROTOCOLS_AUD ADD CONSTRAINT EMS_PRODUCTPROTOCOLS_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE; 

  CREATE TABLE EMS_BATCH_EXECUTION_AUD (
    BATCH_NAME VARCHAR2(50 ), 
    REV NUMBER NOT NULL,
    REVTYPE NUMBER(1),
	EXECUTION_START_TIME TIMESTAMP (6), 
	EXECUTION_END_TIME TIMESTAMP (6), 
	ROWS_PROCESSED NUMBER
	) ;
ALTER TABLE EMS_BATCH_EXECUTION_AUD ADD CONSTRAINT EMS_BATCH_EXECUTION_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;     