DROP INDEX EMS_INST_DATA_I2;
DROP INDEX EMS_INST_DATA_I1;
DROP TABLE EMS_INST_DATA_SECURITY  CASCADE CONSTRAINTS;
DROP TABLE EMS_INST_DATA_SECURITY_AUD  CASCADE CONSTRAINTS;
DROP TABLE BATCH_EXECUTION_INFO  CASCADE CONSTRAINTS;
DROP SEQUENCE EMS_INST_DATA_SECURITY_SEQ;
DROP SEQUENCE HIBERNATE_SEQUENCE;
DROP TABLE REVINFO CASCADE CONSTRAINTS;

CREATE TABLE EMS_INST_DATA_SECURITY (
    INST_ID                 NUMBER,
    ISIN                    CHAR(12),
    CUSIP                   CHAR(9),
    CINS                    CHAR(9),
    BONDTYPE                CHAR(1),
    TRACECODE               CHAR(1),
    SHORTNAME               VARCHAR2(100),
    TICKER                  VARCHAR2(15),
    COUPON                  NUMBER,
    COUPONFREQUENCY         CHAR(1),
    COUPONTYPE              CHAR(1),
    MATURITYDATE            DATE,
    ISSUEDATE               DATE,
    ACCRUALSTARTDATE        DATE,
    NEXTPAYMENTDATE         DATE,
    ISSUEAMOUNT             NUMBER,
    AMOUNTOUTSTANDING       NUMBER,
    CURRENCY                CHAR(3),
    COUNTRY                 CHAR(2),
    ISSUER                  VARCHAR2(255),
    INDUSTRYSECTOR          VARCHAR2(50),
    DEBTCLASSIFICATION      VARCHAR2(20),
    MOODYRATING             VARCHAR2(10),
    SANDPRATING             VARCHAR2(10),
    NEXTCALLDATE            DATE,
    NEXTCALLPRICE           NUMBER,
    NEXTPUTDATE             DATE,
    BENCHMARKID             NUMBER,
    CALCFLAG                CHAR(1),
    DV01WORST               NUMBER,
    MODIFIEDDURATIONWORST   NUMBER,
    MARKETSEGMENTID         NUMBER,
    MARKETSEGMENTCODE       CHAR(2),
    PRODUCTCODE             CHAR(4),
    PRODUCTISDEFAULT        CHAR(1),
    PROTOCOL                VARCHAR2(15),
    ISDELETED               CHAR(1),
    UPDATETS                TIMESTAMP
);

CREATE SEQUENCE EMS_INST_DATA_SECURITY_SEQ START WITH 1 INCREMENT BY 1 CACHE 100;

ALTER TABLE EMS_INST_DATA_SECURITY
    ADD CONSTRAINT EMS_INST_DATA_SECURITY_PK PRIMARY KEY ( INST_ID )
        USING INDEX LOGGING;

CREATE INDEX EMS_INST_DATA_I1 ON
    EMS_INST_DATA_SECURITY ( ISIN );

CREATE INDEX EMS_INST_DATA_I2 ON
    EMS_INST_DATA_SECURITY ( CUSIP );
    
CREATE TABLE REVINFO (
    REV        NUMBER NOT NULL,
    REVTSTMP   NUMBER,
    CONSTRAINT REVINFO_PKEY PRIMARY KEY ( REV )
);    

CREATE TABLE EMS_INST_DATA_SECURITY_AUD (
    INST_ID                 NUMBER,
    REV                     NUMBER NOT NULL,
    REVTYPE                 NUMBER(1),
    ISIN                    CHAR(12),
    CUSIP                   CHAR(9),
    CINS                    CHAR(9),
    BONDTYPE                CHAR(1),
    TRACECODE               CHAR(1),
    SHORTNAME               VARCHAR2(100),
    TICKER                  VARCHAR2(15),
    COUPON                  NUMBER,
    COUPONFREQUENCY         CHAR(1),
    COUPONTYPE              CHAR(1),
    MATURITYDATE            DATE,
    ISSUEDATE               DATE,
    ACCRUALSTARTDATE        DATE,
    NEXTPAYMENTDATE         DATE,
    ISSUEAMOUNT             NUMBER,
    AMOUNTOUTSTANDING       NUMBER,
    CURRENCY                CHAR(3),
    COUNTRY                 CHAR(2),
    ISSUER                  VARCHAR2(255),
    INDUSTRYSECTOR          VARCHAR2(50),
    DEBTCLASSIFICATION      VARCHAR2(20),
    MOODYRATING             VARCHAR2(10),
    SANDPRATING             VARCHAR2(10),
    NEXTCALLDATE            DATE,
    NEXTCALLPRICE           NUMBER,
    NEXTPUTDATE             DATE,
    BENCHMARKID             NUMBER,
    CALCFLAG                CHAR(1),
    DV01WORST               NUMBER,
    MODIFIEDDURATIONWORST   NUMBER,
    MARKETSEGMENTID         NUMBER,
    MARKETSEGMENTCODE       CHAR(2),
    PRODUCTCODE             CHAR(4),
    PRODUCTISDEFAULT        CHAR(1),
    PROTOCOL                VARCHAR2(15),
    ISDELETED               CHAR(1),
    UPDATETS                TIMESTAMP
);
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 100;

ALTER TABLE EMS_INST_DATA_SECURITY_AUD ADD CONSTRAINT EMS_INST_DATA_SECURITY_AUD_R FOREIGN KEY (REV) REFERENCES REVINFO(REV) ENABLE;

CREATE TABLE BATCH_EXECUTION_INFO (
    BATCH_NAME                 VARCHAR2(50),
    LAST_EXECUTION_TIMESTAMP   TIMESTAMP
);

ALTER TABLE BATCH_EXECUTION_INFO ADD CONSTRAINT BATCH_EXECUTION_INFO_PK PRIMARY KEY ( BATCH_NAME );

