package com.mktx.ems.order.model;

public enum Event {

	ORDER_NEW_RECEIVED,
	ORDER_NEW_ACCEPTED,
	ORDER_NEW_REJECTED,

	ORDER_CANCEL_RECEIVED,
	ORDER_CANCEL_ACCEPTED,
	ORDER_CANCEL_REJECTED,

	INQUIRY_NEW_SUBMITTED,
	INQUIRY_NEW_ACCEPTED,
	INQUIRY_NEW_REJECTED,

	INQUIRY_CANCEL_SUBMITTED,
	INQUIRY_CANCEL_ACCEPTED,
	INQUIRY_CANCEL_REJECTED,

	QUOTE_CPTY_RESPONDED,
	QUOTE_CPTY_TIMEDOUT,
	QUOTE_CPTY_PASSED,
	QUOTE_CPTY_EXPIRED,
	QUOTE_CPTY_CANCELLED,

	QUOTE_PASS_SUBMITTED,
	QUOTE_PASS_ACCEPTED,
	QUOTE_PASS_REJECTED,

	QUOTE_COUNTER_SUBMITTED,
	QUOTE_COUNTER_ACCEPTED,
	QUOTE_COUNTER_REJECTED,

	QUOTE_HITLIFT_SUBMITTED,
	QUOTE_HITLIFT_ACCEPTED,
	QUOTE_HITLIFT_REJECTED,

	TRADE_DONE,
}
