DROP TABLE INSTRUMENT_MASTERSECURITY CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENT_SECTOR CASCADE CONSTRAINTS;
DROP TABLE UTIL_CURRENCY CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENT_MARKETSEGMENT CASCADE CONSTRAINTS;
DROP TABLE UTIL_CALENDAR CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENT_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENT_PRODUCTINSTRUMENTS CASCADE CONSTRAINTS;
DROP TABLE INSTRUMENT_PRODUCTPROTOCOLS CASCADE CONSTRAINTS;
DROP TABLE INQUIRY_TRADINGPROTOCOL CASCADE CONSTRAINTS;
DROP TABLE UTIL_TEMAP CASCADE CONSTRAINTS;


  CREATE TABLE INSTRUMENT_MASTERSECURITY (	
    ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(255 ) NOT NULL ENABLE, 
	COUPON NUMBER NOT NULL ENABLE, 
	MATURITY DATE NOT NULL ENABLE, 
	CUSIP VARCHAR2(30 ) NOT NULL ENABLE, 
	ISSUEDATE DATE, 
	ACCRUALSTART DATE, 
	FIRSTPAYMENT DATE, 
	SECONDPAYMENT DATE, 
	PAYMENTTYPE CHAR(1 ), 
	INTERESTRATETYPE CHAR(1 ), 
	BONDTYPE CHAR(1 ), 
	DEFAULTED CHAR(1 ), 
	ACCRUALMETHOD CHAR(1 ), 
	PAYMENTFREQUENCY CHAR(1 ), 
	REDEMPTION NUMBER, 
	TRAILER VARCHAR2(255 ), 
	DESCRIPTION VARCHAR2(500 ), 
	ISDELETED CHAR(1 ) DEFAULT 'N' NOT NULL ENABLE, 
	ISMULTICOUPON CHAR(1 ) DEFAULT 'N' NOT NULL ENABLE, 
	TIMESTAMP DATE NOT NULL ENABLE, 
	LASTPAYMENT DATE, 
	ISIN VARCHAR2(12 ), 
	COUNTRYCODE VARCHAR2(4 ), 
	CLEARINGHOUSE VARCHAR2(10 ), 
	MINLOTSIZE NUMBER, 
	MARKETSEGMENT NUMBER, 
	MARKETCATEGORY NUMBER, 
	MARKETSUBCATEGORY NUMBER, 
	COMMISSIONRATE NUMBER, 
	FRNINDEX VARCHAR2(20 ), 
	FRNBASIS NUMBER, 
	SHORTNAME VARCHAR2(100 ), 
	ISSUER VARCHAR2(255 ), 
	ISCVTPREFSTOCK CHAR(1 ), 
	PARVALUE NUMBER, 
	FITCHRATING NUMBER, 
	SNPRATING NUMBER, 
	MOODYRATING NUMBER, 
	ISOCURRENCYCODE CHAR(3 ), 
	SECTORID NUMBER, 
	NOUPDATEFROMFEED CHAR(1 ) DEFAULT 'N' NOT NULL ENABLE, 
	ISSUEAMOUNT NUMBER, 
	AMOUNTOUTSTANDING NUMBER, 
	FIRSTSETTLEMENTDATE DATE, 
	CALLABLE CHAR(1 ), 
	PUTABLE CHAR(1 ), 
	SINKABLE CHAR(1 ), 
	MAKEWHOLE CHAR(1 ), 
	NEXTCALLDATE DATE, 
	NEXTPUTDATE DATE, 
	NEXTSINKDATE DATE, 
	SECURITYTYPE VARCHAR2(32 ), 
	FLTFORMULA VARCHAR2(255 ), 
	FLTMULT NUMBER, 
	FLTCAP NUMBER, 
	FLTFLOOR NUMBER, 
	VENDORNAME VARCHAR2(65 ), 
	DEBT_TYPE_CD VARCHAR2(20 ), 
	CALC_ISSUE CHAR(1 ), 
	EOM_FLAG CHAR(1 ), 
	ORIGINAL_COUPON NUMBER, 
	DEFAULTTICKER VARCHAR2(15 ), 
	VENDORBONDID NUMBER, 
	TOKENIZEDSHORTNAME VARCHAR2(175 ), 
	SYNDICATED CHAR(1 ) DEFAULT 'N', 
	DENOMINCR NUMBER, 
	DV01_WORST NUMBER, 
	MOD_DUR_WORST NUMBER, 
	REDPAIRCLIP VARCHAR2(9 ), 
	WKN VARCHAR2(6 ), 
	BMKATISSUEID NUMBER, 
	SEASONED CHAR(1 ), 
	LEADUNDERWRITER VARCHAR2(300 ), 
	CALC_TRACE CHAR(1 ), 
	FDIC CHAR(1 ), 
	ISSUEPRICE NUMBER, 
	NEXTPAYDATE DATE, 
	EXDIVDATE DATE, 
	CUMULDIV CHAR(1 ), 
	INITIALDIV NUMBER, 
	ANNUALDIV NUMBER, 
	SEDOL VARCHAR2(7 ), 
	COLLAT_GROSS_CPN NUMBER, 
	COLLAT_NET_CPN NUMBER, 
	COLLAT_REM_TERM NUMBER, 
	COUPON_DATE DATE, 
	COUPON_EFF_DATE DATE, 
	COUPON_UPDATE_DATE DATE, 
	DEAL_TYPE VARCHAR2(100 ), 
	DELAY_DAYS NUMBER, 
	EXPECTED_MAT_DATE DATE, 
	FACTOR NUMBER, 
	FACTOR_DATE DATE, 
	FLT_INIT_RESET_DATE DATE, 
	FLT_RESET_FREQ CHAR(1 ), 
	MATURITY_AVG_LIFE NUMBER, 
	MATURITY_AVG_LIFE_DATE DATE, 
	MATURITY_PREPAY_MODEL VARCHAR2(5 ), 
	MATURITY_PREPAY_SPEED NUMBER, 
	ORIGINAL_AVG_LIFE NUMBER, 
	PRICE_SPEED NUMBER, 
	PRICE_SPEED_METHOD VARCHAR2(8 ), 
	PRICED_DATE DATE, 
	SERIES VARCHAR2(20 ), 
	TRANCHE VARCHAR2(20 ), 
	TRANCHE_CHAR VARCHAR2(100 ), 
	TRUSTEE VARCHAR2(100 ), 
	IBOXX_SECTORID NUMBER, 
	COLLAT_TYPE VARCHAR2(100 ), 
	HAS_ARM_COLLAT VARCHAR2(10 ), 
	INIT_ARM_RESET_PER NUMBER, 
	MTN CHAR(1 ), 
	CINS VARCHAR2(10 ), 
	TRACE_CODE CHAR(1 ), 
	DEFAULT_PRODUCTID_EU NUMBER, 
	SUBORDINATION_CLAUSE VARCHAR2(20 ), 
	SETTLE_DAYS NUMBER, 
	OT_DISABLED VARCHAR2(20 ), 
	FEED_PRICE NUMBER, 
	OUTSTANDING_INDICATOR CHAR(1 ), 
	FEDERAL_TAX_STATUS VARCHAR2(80 ), 
	INCORPORATED_STATE_CODE VARCHAR2(2 ), 
	ORGANIZATION_TYPE VARCHAR2(80 ), 
	CONDUIT_OBLIGOR_NAME VARCHAR2(75 ), 
	ORIGINAL_YIELD FLOAT(126), 
	MATURITY_AMOUNT FLOAT(126), 
	BANK_ELIGIBLE CHAR(1 ), 
	BANK_QUALIFIED CHAR(1 ), 
	AMT CHAR(1 ), 
	ETM CHAR(1 ), 
	PREREFUNDED CHAR(1 ), 
	REGISTERED CHAR(1 ), 
	TAXABLE CHAR(1 ), 
	TOBACCO CHAR(1 ), 
	BOND_INSURANCE VARCHAR2(50 ), 
	OTHER_ENHANCEMENT_COMPANY VARCHAR2(50 ), 
	MOODY_UNDERLYING_RATING NUMBER, 
	SNP_UNDERLYING_RATING NUMBER, 
	FITCH_UNDERLYING_RATING NUMBER, 
	GENERAL_OBLIGATION CHAR(1 ), 
	REVENUE CHAR(1 ), 
	DOUBLE_BARREL CHAR(1 ), 
	NEXT_PRERE_DATE DATE, 
	DISPLAY_CALL_DATE DATE, 
	DISPLAY_CALL_TYPE VARCHAR2(20 ), 
	DISPLAY_CALL_PRICE FLOAT(126), 
	ISSUER_ABBREV_NAME VARCHAR2(255 ), 
	PURPOSE VARCHAR2(50 ), 
	AGENT_BANK VARCHAR2(255 ), 
	DEAL_CUSIP VARCHAR2(25 ), 
	DEAL_NAME VARCHAR2(255 ), 
	DEAL_GLOBAL_AMOUNT NUMBER(15,4), 
	DEAL_EFF_DATE DATE, 
	LOANX VARCHAR2(50 ), 
	IS_FIXED CHAR(1 ), 
	IS_GUARANTEED CHAR(1 ), 
	EQUITY_TICKER VARCHAR2(50 ), 
	ASSIGNMENT_FEE NUMBER(15,4), 
	PUBLIC_LOAN VARCHAR2(10 ), 
	CALL_SCHEDULE_DATE DATE, 
	LIEN_TYPE VARCHAR2(50 ), 
	GUARANTOR VARCHAR2(254 ), 
	INTERBANK_ID VARCHAR2(20 ), 
	EXCH_CD VARCHAR2(3 ), 
	PERPETUAL_FL CHAR(1 ), 
	CFI_CD VARCHAR2(10 ), 
	ISSUER_LEI_CD VARCHAR2(30 ), 
	ESMA_BOND_TYPE VARCHAR2(10 ), 
	LIQUIDITY_FLAG CHAR(1 ), 
	COFIA_LIQUIDITY_FLAG CHAR(1 ), 
	LIS_SIZE NUMBER, 
	SSTI_SIZE NUMBER, 
	SUSPEND_FLAG CHAR(1 ), 
	MIFIR_INDICATOR VARCHAR2(10 ), 
	MIFID_SI VARCHAR2(30 ), 
	ON_MAEL CHAR(1 ), 
	ON_MTXX CHAR(1 ), 
	ON_MASG CHAR(1 ), 
	ASSET_STATUS VARCHAR2(3 ), 
	FCA_LIQUIDITY_FLAG CHAR(1 ), 
	FCA_LIS_SIZE NUMBER, 
	FCA_SSTI_SIZE NUMBER, 
	FCA_SUSPEND_FLAG CHAR(1 ), 
	ON_MANL CHAR(1 ), 
	FI_INDEX_IDENTIFIER VARCHAR2(20 ), 
	FI_INDEX_NAME VARCHAR2(30 ), 
	FI_INDEX_TERM VARCHAR2(10 ), 
	FI_BASE_POINT_SPREAD NUMBER, 
	FI_ESMA_INDEX_IDENTIFIER VARCHAR2(20 ), 
	FI_ESMA_INDEX_NAME VARCHAR2(30 ), 
	FI_ESMA_INDEX_TERM VARCHAR2(10 ), 
	FI_ESMA_BASE_POINT_SPREAD NUMBER, 
	SD_DELIVERY_TYPE VARCHAR2(5 ), 
	SD_ESMA_DELIVERY_TYPE VARCHAR2(5 ), 
	CD_UNDERLY_CDS_ISIN VARCHAR2(15 ), 
	UNDERLY_ISIN VARCHAR2(15 ), 
	MAEL_TERMINATION_DATE DATE, 
	MANL_TERMINATION_DATE DATE, 
	MAEL_ADMISSION_DATE DATE, 
	MANL_ADMISSION_DATE DATE, 
	 CONSTRAINT BONDTYPES CHECK (BONDTYPE IN (NULL, 'R', '1')) ENABLE, 
	 CONSTRAINT DEFTYPES CHECK (DEFAULTED IN (NULL, 'Y', 'N')) ENABLE, 
	 CONSTRAINT DELTYPES CHECK (ISDELETED IN ('Y', 'y', 'n', 'N')) ENABLE, 
	 CONSTRAINT INTTYPES CHECK (INTERESTRATETYPE IN (NULL, 'F', 'V', 'Z', 'N')) ENABLE, 
	 CONSTRAINT MCTYPES CHECK (ISMULTICOUPON IN ('Y', 'y', 'n', 'N')) ENABLE, 
	 CONSTRAINT PAYTYPES CHECK (PAYMENTTYPE IN (NULL, 'C', 'P', 'A', 'Z')) ENABLE, 
	 CONSTRAINT PK_INSTRUMENT_MS PRIMARY KEY (ID)
  
   );

  CREATE INDEX DEAL_CUSIP_IDX ON INSTRUMENT_MASTERSECURITY (DEAL_CUSIP);

  CREATE INDEX INSTRUMENT_MS_COUNTRYCODE ON INSTRUMENT_MASTERSECURITY (COUNTRYCODE);

  CREATE INDEX INSTRUMENT_MS_COUPON ON INSTRUMENT_MASTERSECURITY (COUPON);

  CREATE INDEX INSTRUMENT_MS_CUSIP ON INSTRUMENT_MASTERSECURITY (CUSIP);

  CREATE INDEX INSTRUMENT_MS_CUSIP6 ON INSTRUMENT_MASTERSECURITY (SUBSTR(CUSIP,0,6));

  CREATE INDEX INSTRUMENT_MS_CUSIP8 ON INSTRUMENT_MASTERSECURITY (SUBSTR(CUSIP,0,8));

  CREATE INDEX INSTRUMENT_MS_FITCH ON INSTRUMENT_MASTERSECURITY (FITCHRATING);

  CREATE INDEX INSTRUMENT_MS_GEN_OBLIGATION ON INSTRUMENT_MASTERSECURITY (GENERAL_OBLIGATION);

  CREATE INDEX INSTRUMENT_MS_INSURANCE ON INSTRUMENT_MASTERSECURITY (BOND_INSURANCE);

  CREATE INDEX INSTRUMENT_MS_INTERBANK_ID ON INSTRUMENT_MASTERSECURITY (INTERBANK_ID);

  CREATE INDEX INSTRUMENT_MS_ISIN ON INSTRUMENT_MASTERSECURITY (ISIN);

  CREATE INDEX INSTRUMENT_MS_ISSUER ON INSTRUMENT_MASTERSECURITY (ISSUER);

  CREATE INDEX INSTRUMENT_MS_ISSUER_MATURITY ON INSTRUMENT_MASTERSECURITY (ISSUER, MATURITY);

  CREATE INDEX INSTRUMENT_MS_MKTSEG ON INSTRUMENT_MASTERSECURITY (MARKETSEGMENT);

  CREATE INDEX INSTRUMENT_MS_MOODY ON INSTRUMENT_MASTERSECURITY (MOODYRATING);

  CREATE INDEX INSTRUMENT_MS_NAME ON INSTRUMENT_MASTERSECURITY (NAME);

  CREATE INDEX INSTRUMENT_MS_REVENUE ON INSTRUMENT_MASTERSECURITY (REVENUE) ;

  CREATE INDEX INSTRUMENT_MS_SHORTNAME ON INSTRUMENT_MASTERSECURITY (SHORTNAME);

  CREATE INDEX INSTRUMENT_MS_SNP ON INSTRUMENT_MASTERSECURITY (SNPRATING);

  CREATE INDEX INSTRUMENT_MS_STATECD ON INSTRUMENT_MASTERSECURITY (INCORPORATED_STATE_CODE);

  CREATE INDEX INSTRUMENT_MS_TICKER ON INSTRUMENT_MASTERSECURITY (DEFAULTTICKER);

  CREATE INDEX INSTRUMENT_MS_TIMESTAMP ON INSTRUMENT_MASTERSECURITY (TIMESTAMP);

  CREATE INDEX INSTRUMENT_MS_UNDER_FITCH ON INSTRUMENT_MASTERSECURITY (FITCH_UNDERLYING_RATING);

  CREATE INDEX INSTRUMENT_MS_UNDER_MOODY ON INSTRUMENT_MASTERSECURITY (MOODY_UNDERLYING_RATING);

  CREATE INDEX INSTRUMENT_MS_UNDER_SNP ON INSTRUMENT_MASTERSECURITY (SNP_UNDERLYING_RATING);

  CREATE INDEX INSTRUMENT_MS_VENDORID ON INSTRUMENT_MASTERSECURITY (VENDORBONDID);

  CREATE INDEX INSTRUMENT_MS_WKN ON INSTRUMENT_MASTERSECURITY (WKN);

  CREATE INDEX LOANX_IDX ON INSTRUMENT_MASTERSECURITY (LOANX);


CREATE TABLE INSTRUMENT_SECTOR (	
    ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(50) NOT NULL ENABLE, 
	SEQUENCE NUMBER NOT NULL ENABLE, 
	TYPE VARCHAR2(10 ) DEFAULT 'BOND' NOT NULL ENABLE, 
	SHORTNAME VARCHAR2(11)
);

ALTER TABLE INSTRUMENT_SECTOR ADD CONSTRAINT PK_ISECTOR PRIMARY KEY (ID);



CREATE TABLE UTIL_CURRENCY (	
	ISOCODE CHAR(3 ) NOT NULL ENABLE, 
	LONGNAME VARCHAR2(250 ) NOT NULL ENABLE, 
	SHORTNAME CHAR(3 ) NOT NULL ENABLE, 
	PREPENDSYMBOL CHAR(1 ) NOT NULL ENABLE, 
	APPENDSYMBOL CHAR(1 ) NOT NULL ENABLE, 
	MINORUNIT NUMBER NOT NULL ENABLE, 
	TEXTSYMBOL VARCHAR2(4 ), 
	UNICODESYMBOL VARCHAR2(32 ), 
	POSTFIXSYMBOL VARCHAR2(32 ), 
	MFD_FXRATE_EUR NUMBER
);
ALTER TABLE UTIL_CURRENCY ADD CONSTRAINT PK_UTIL_CURRENCY PRIMARY KEY (ISOCODE);

CREATE TABLE INSTRUMENT_MARKETSEGMENT (	
    ID NUMBER NOT NULL ENABLE, 
	MARKETSEGMENT VARCHAR2(4 ) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	POSTTRADEMARKETSEGMENT VARCHAR2(15 )
	);
ALTER TABLE INSTRUMENT_MARKETSEGMENT ADD CONSTRAINT PK_INSTRUMENT_MARKETSEGMENT PRIMARY KEY (ID);

CREATE TABLE UTIL_CALENDAR (	
	CALENDARID NUMBER NOT NULL ENABLE, 
	CODE VARCHAR2(4 ), 
	DESCRIPTION VARCHAR2(50 ), 
	DISPLAYNAME VARCHAR2(50 )
   )  ;
ALTER TABLE UTIL_CALENDAR ADD CONSTRAINT PK_UTIL_CALENDAR_ID PRIMARY KEY (CALENDARID);

  CREATE TABLE INSTRUMENT_PRODUCT 
   (	ID NUMBER NOT NULL ENABLE, 
	MARKETSEGMENTID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	PRODUCT_CD CHAR(4 ), 
	CALENDARID NUMBER DEFAULT 0 NOT NULL ENABLE, 
	REGIONID NUMBER, 
	APPLY_FEE CHAR(1 ) DEFAULT 'N', 
	VISIBLEPRODUCTID NUMBER, 
	ACCEPTSBMK CHAR(1 ), 
	STLDAYS NUMBER DEFAULT 3 NOT NULL ENABLE, 
	FXSTLDAYS NUMBER DEFAULT 3 NOT NULL ENABLE, 
	BMKPRODUCTID NUMBER, 
	LEVEL_INCREMENT NUMBER, 
	ISDELETED CHAR(1 ) DEFAULT 'N' NOT NULL ENABLE, 
	CCPNAME VARCHAR2(10 )
   );

CREATE INDEX INSTRUMENT_PRODUCT_PRD ON INSTRUMENT_PRODUCT (PRODUCT_CD); 
ALTER TABLE INSTRUMENT_PRODUCT ADD CONSTRAINT PK1_INSTRUMENT_PRODUCT PRIMARY KEY (ID);
ALTER TABLE INSTRUMENT_PRODUCT ADD( 
			CONSTRAINT FK1_INSTRUMENT_PROD_MS FOREIGN KEY (MARKETSEGMENTID)
					REFERENCES INSTRUMENT_MARKETSEGMENT (ID) ENABLE, 
			CONSTRAINT FK1_INST_PROD_CAL_ID FOREIGN KEY (CALENDARID)
					REFERENCES UTIL_CALENDAR (CALENDARID) ENABLE
					);
                    

  CREATE TABLE INSTRUMENT_PRODUCTINSTRUMENTS 
   (	INSTRUMENTID NUMBER NOT NULL ENABLE, 
	PRODUCTID NUMBER NOT NULL ENABLE, 
	ISDEFAULT CHAR(1 ), 
	PRIORITY NUMBER(*,0)	
   ) ;
   
ALTER TABLE INSTRUMENT_PRODUCTINSTRUMENTS ADD CONSTRAINT PK_INSTRUMENT_PRODINST PRIMARY KEY (INSTRUMENTID, PRODUCTID);
   
ALTER TABLE INSTRUMENT_PRODUCTINSTRUMENTS ADD(
		CONSTRAINT FK_INSTRUMENT_PRODINST_PROD FOREIGN KEY (PRODUCTID)
			REFERENCES INSTRUMENT_PRODUCT (ID) ENABLE, 
		CONSTRAINT FK_INSTRUMENT_PRODINST_INST FOREIGN KEY (INSTRUMENTID)
	  REFERENCES INSTRUMENT_MASTERSECURITY (ID) ENABLE
	  );

  CREATE TABLE INSTRUMENT_PRODUCTPROTOCOLS (
	ID NUMBER, 
	PRODUCTID NUMBER NOT NULL ENABLE, 
	INQUIRYTYPE CHAR(1 ), 
	PRICETYPE CHAR(1 ), 
	TRANSACTIONTYPE VARCHAR2(8 ), 
	PROTOCOLID NUMBER, 
	FORCERANK NUMBER NOT NULL ENABLE
	);
    
ALTER TABLE INSTRUMENT_PRODUCTPROTOCOLS ADD CONSTRAINT PK_INST_PRODPROTOCOLS PRIMARY KEY (ID);
CREATE UNIQUE INDEX INST_PRODPROTOCOLS_PROTOCOL ON INSTRUMENT_PRODUCTPROTOCOLS (PRODUCTID, INQUIRYTYPE, PRICETYPE, TRANSACTIONTYPE, PROTOCOLID) ;
CREATE UNIQUE INDEX INST_PRODPROTOCOLS_RANK ON INSTRUMENT_PRODUCTPROTOCOLS (PRODUCTID, INQUIRYTYPE, PRICETYPE, TRANSACTIONTYPE, FORCERANK);


CREATE TABLE INQUIRY_TRADINGPROTOCOL (	
	TRADINGPROTOCOLID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(32 ), 
	SHORTNAME VARCHAR2(15 ), 
	APINAME VARCHAR2(10 )  
   );
   
ALTER TABLE INQUIRY_TRADINGPROTOCOL ADD CONSTRAINT INQUIRY_TRADINGPROTOCOL_PK PRIMARY KEY (TRADINGPROTOCOLID);


  CREATE TABLE UTIL_TEMAP (	
	TYPE NUMBER NOT NULL ENABLE, 
	ID NUMBER NOT NULL ENABLE, 
	SHORTSTRING VARCHAR2(40 ), 
	LONGSTRING VARCHAR2(120 ), 
	VISIBLE CHAR(1 ) NOT NULL ENABLE, 
	ISDELETED CHAR(1 ) NOT NULL ENABLE
   );

CREATE INDEX UTIL_TEMAP_TYPE ON UTIL_TEMAP (TYPE);
ALTER TABLE UTIL_TEMAP ADD CONSTRAINT PK_UTIL_TEMAP PRIMARY KEY (TYPE, ID);