CREATE TABLE EMS_ORDER (
    ID                           NUMERIC NOT NULL,
    SENDER_COMPANY               VARCHAR(100),
    ON_BEHALF_OF_COMPANY         VARCHAR(100),
    TRANSACTION_TS               TIMESTAMP,
    CLIENT_ORDER_ID              VARCHAR(100),
    CREATE_TS                    TIMESTAMP,
    UPDATE_TS                    TIMESTAMP,
    LAST_CHANGE_USER             VARCHAR(50),
    ASSIGNED_TO                  VARCHAR(50),
    STATUS                       VARCHAR(16),
    ISIN                         VARCHAR(12),
    CUSIP                        VARCHAR(9),
    CURRENCY                     VARCHAR(3),
    BENCHMARK_ISIN               VARCHAR(12),
    BENCHMARK_CURVE_NAME         VARCHAR(50),
    BENCHMARK_CURVE_POINT        VARCHAR(50),
    YIELD_TO_DATE_TYPE           VARCHAR(20),
    YIELD_TO_DATE                DATE,
    SIDE                         VARCHAR(50),
    SIZE_ORIGINAL                NUMERIC,
    SIZE_REMAINING               NUMERIC,
    SIZE_OPEN                    NUMERIC,
    SIZE_FILLED                  NUMERIC,
    VENUE_ON_ORDER               VARCHAR(4),
    ORDER_TYPE                   VARCHAR(16),
    LIMIT_PRICE                  NUMERIC,
    LIMIT_PRICE_TYPE             VARCHAR(4),
    EXPIRY_TYPE                  VARCHAR(3),
    EXPIRY_TS                    TIMESTAMP,
    TRADER_ID                    VARCHAR(100),
    CLIENT_ID                    VARCHAR(100),
    INVESTMENT_DECISION_MAKER    VARCHAR(100),
    SETTLEMENT_TYPE_ON_ORDER     VARCHAR(100),
    SETTLEMENT_DATE_ON_ORDER     DATE,
    INQUIRIES_SUBMITTED          NUMERIC,
    INQUIRIES_OPEN               NUMERIC,
    INQUIRIES_PARTIALLY_FILLED   NUMERIC,
    INQUIRIES_FILLED             NUMERIC,
    INQUIRIES_NOT_TRADED         NUMERIC,
    INQUIRIES_CANCELLED          NUMERIC,
    VWA_PRICE                    NUMERIC,
    VWA_SPREAD                   NUMERIC,
    VWA_YIELD                    NUMERIC,
    FIRM_ID                      VARCHAR(50),
    QUANTITY                     NUMERIC,
    QUANTITY_TYPE                VARCHAR(50),
    PROTOCOL                     VARCHAR(50),
    PRICING_PROCESS              NUMERIC,
    SOURCE                       VARCHAR(50),
    INST_ID                      NUMERIC,
    DIRECTION                    VARCHAR(50),
    ALGORITHM                    VARCHAR(50),
    CAPACITY                     VARCHAR(50),
    AUTO_EXECUTION               BOOLEAN DEFAULT '0',
    ACTIVE                       BOOLEAN DEFAULT '0',
    ORDER_TS                     TIMESTAMP,
    SENDING_TS                   TIMESTAMP,
    SECURITY_ID                  VARCHAR(20),
    HANDLING_INST                NUMERIC,
    CLIENT_NOTES                 VARCHAR(1000),
    PORTFOLIO_NAME               VARCHAR(1000),
    BUY_SELL_DECISION_MAKER      VARCHAR(50),
    CLIENT_TRADER_SHORT_CODE     VARCHAR(50),
    BENCHMARK_ID_SOURCE          VARCHAR(8),
    BENCHMARK_SECURITY_ID        VARCHAR(20),
    REASON                       VARCHAR(1000),
    FIX_CONNECTION_ID            NUMERIC,
    EXECID                       VARCHAR(50)
);
ALTER TABLE EMS_ORDER ADD CONSTRAINT EMS_ORDER_PK PRIMARY KEY (ID);
CREATE INDEX EMS_ORDER_I1 ON EMS_ORDER(FIRM_ID, CLIENT_ORDER_ID);
CREATE INDEX EMS_ORDER_I2 ON EMS_ORDER(CREATE_TS);

INSERT INTO EMS_ORDER (ID,CLIENT_ORDER_ID,FIRM_ID,QUANTITY,CURRENCY,SOURCE,ISIN,INST_ID,ACTIVE,DIRECTION,ORDER_TYPE,TRADER_ID,CAPACITY,
					  LIMIT_PRICE,LIMIT_PRICE_TYPE,ORDER_TS,CREATE_TS,EXPIRY_TS)
					  VALUES(1,'Order1','FIRM2',200,'USD','GUI','GB2222222222',2,'1','BUY','MARKET','user2','PRIN',20.111,'YIEL','2019-01-01 00:00:00','2019-01-02 00:00:00','2099-01-01 00:00:00');